# Generated by Django 4.0 on 2022-04-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_Id', models.AutoField(primary_key=True, serialize=False)),
                ('department_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_Id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_Name', models.CharField(max_length=255)),
                ('Join_date', models.DateField()),
                ('profile_Name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeData.department')),
            ],
        ),
    ]
